# Generated by Django 3.0.8 on 2020-07-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_layout_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
