# Generated by Django 3.0.8 on 2020-07-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_layout_app', '0002_destination_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='destination',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
